runtime: python39
service: default

handlers:
- url: /src/images
  static_dir: images

- url: /(.*\.(css|js|png|jpg|jpeg|ico))$
  static_files: \1
  upload: (.*\.(css|js|png|jpg|jpeg|ico))$

- url: /
  static_files: index.html
  upload: index.html
