runtime: python27  # Use Python runtime for static file serving
service: default
api_version: 1
threadsafe: true

handlers:
  - url: /(.*\.(html|css|js))$
    static_files: \1
    upload: (.*\.(html|css|js))$
  - url: /.*
    static_files: index.html
    upload: index.html
